name: 17 - custom actions - composite

on:
  workflow_dispatch:

env:
  working-directory: .github/workflows/17-customs-actions/react-app
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node and npm dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 21.x
          working-dir: ${{ env.working-directory }}
          target-env: development

      - name: test
        run: npm test -- --watch=false
        continue-on-error: true

      - name: build
        run: npm run build
