name: 17 - 1 - custom actions - composite

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "dev or prod"
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: .github/workflows/17-customs-actions/react-app
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node and npm dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 21.x
          working-dir: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}

      - name: test
        run: |
          cd ${{ env.working-directory }}
          CI=true npm test -- --watch=false --runInBand --ci --passWithNoTests
        continue-on-error: true

      - name: build
        run: |
          cd ${{ env.working-directory }}
          CI=true npm run build
        continue-on-error: true
